### PR TITLE
It is YouTube and Facebook

### PR DESCRIPTION
**Pull request by kjacobsen**

### CODE REVIEW

**Comment by MattDavies** [comment]
There is also src\util\index.js, and the snapshot tests need updating as well.

**Comment by mderriey** [comment]
@MattDavies @vanbujm

Any pointers on how to update the snapshots?
Some failing tests are unrelated to this PR.

**Comment by mderriey** [comment]
My bad, I asked before looking for the asnwer myself.

**Comment by vanbujm** [comment]
> My bad, I asked before looking for the answer myself.
> 
> * removed all `__snapshots__` directories; and
> * ran `npm run test`

You really should run `npm run test -u` to update instead of deleting all the snapshot directories. 
That way you can review the snapshot diffs and make sure the changes are indeed what you expect.

**Comment by vanbujm** [comment]
@kjacobsen Can you please move these changes onto a branch in this repo instead of merging from a fork? It makes the PR way harder to review as I have to now clone your repo.

**Comment by mderriey** [comment]
@vanbujm Thanks, will know for next time; I did what you suggested locally and the changes are similar than the commit I already pushed.

Any chance you could add the fork as a remote and review it this way instead of cloning a new repo?

```
git remote add kj https://github.com/kjacobsen/readify-signatures
git fetch kj
git checkout kj/master
```

**Pull request merged**
